# Generated by Django 5.0.6 on 2024-07-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Available"),
                            (2, "Rented"),
                            (3, "In Maintenance"),
                            (4, "Lost"),
                            (5, "Sold"),
                        ],
                        default=1,
                    ),
                ),
                ("rental_cost_per_hour", models.FloatField()),
            ],
        ),
    ]
