# Generated by Django 5.0.6 on 2024-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bike",
            options={"verbose_name": "Велосипед", "verbose_name_plural": "Велосипеды"},
        ),
        migrations.AlterField(
            model_name="bike",
            name="rental_cost_per_hour",
            field=models.FloatField(
                help_text="Стоимость аренды велосипеда за один час (в рублях)",
                verbose_name="Стоимость аренды",
            ),
        ),
        migrations.AlterField(
            model_name="bike",
            name="serial_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Серийный номер"
            ),
        ),
        migrations.AlterField(
            model_name="bike",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Доступен"),
                    (2, "Арендован"),
                    (3, "На обслуживании"),
                    (4, "Утерян"),
                    (5, "Продан"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
