# Generated by Django 5.0.6 on 2024-07-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0002_alter_bike_options_alter_bike_rental_cost_per_hour_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bike",
            options={
                "ordering": ("serial_number",),
                "verbose_name": "Велосипед",
                "verbose_name_plural": "Велосипеды",
            },
        ),
    ]
