# Generated by Django 5.0.6 on 2024-07-04 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bikes", "0002_alter_bike_options_alter_bike_rental_cost_per_hour_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время окончания"
                    ),
                ),
                (
                    "total_cost",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Итоговая стоимость"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Активная поездка"), (0, "Завершенная поездка")],
                        default=1,
                        verbose_name="Статус поездки",
                    ),
                ),
                (
                    "bike",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rentals",
                        to="bikes.bike",
                        verbose_name="Велосипед",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Арендатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аренда",
                "verbose_name_plural": "Аренды",
            },
        ),
    ]
