# Generated by Django 5.0.6 on 2024-07-05 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0002_alter_bike_options_alter_bike_rental_cost_per_hour_and_more"),
        ("rental", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rental",
            options={
                "ordering": ("-start_time",),
                "verbose_name": "Аренда",
                "verbose_name_plural": "Аренды",
            },
        ),
        migrations.AlterField(
            model_name="rental",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Действующая аренда"), (0, "Завершенная аренда")],
                default=1,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="total_cost",
            field=models.FloatField(
                blank=True,
                help_text="Итоговая стоимость аренды, выраженная в рублях.",
                null=True,
                verbose_name="Итоговая стоимость",
            ),
        ),
        migrations.AddConstraint(
            model_name="rental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", 1)),
                fields=("user",),
                name="unique_active_rental_for_user",
            ),
        ),
    ]
